//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaSdkWrapper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaSdkWrapper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 可见光红外光像差过大 的本地化字符串。
        /// </summary>
        internal static string ERR_ABERRATION_TOO_BIG {
            get {
                return ResourceManager.GetString("ERR_ABERRATION_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸俯仰角太大 的本地化字符串。
        /// </summary>
        internal static string ERR_ANGLE_PITCH {
            get {
                return ResourceManager.GetString("ERR_ANGLE_PITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸不正 的本地化字符串。
        /// </summary>
        internal static string ERR_ANGLE_ROLL {
            get {
                return ResourceManager.GetString("ERR_ANGLE_ROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸侧偏角太大 的本地化字符串。
        /// </summary>
        internal static string ERR_ANGLE_YAW {
            get {
                return ResourceManager.GetString("ERR_ANGLE_YAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启应用程序失败 的本地化字符串。
        /// </summary>
        internal static string ERR_APP_REBOOT {
            get {
                return ResourceManager.GetString("ERR_APP_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证失败 的本地化字符串。
        /// </summary>
        internal static string ERR_AUTH_FAILED {
            get {
                return ResourceManager.GetString("ERR_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩图像失败 的本地化字符串。
        /// </summary>
        internal static string ERR_ENCODE_JPG {
            get {
                return ResourceManager.GetString("ERR_ENCODE_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取特征失败 的本地化字符串。
        /// </summary>
        internal static string ERR_EXTRACT_FEATURE {
            get {
                return ResourceManager.GetString("ERR_EXTRACT_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在相似人脸 的本地化字符串。
        /// </summary>
        internal static string ERR_FACE_EXISTED {
            get {
                return ResourceManager.GetString("ERR_FACE_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改人脸特征失败（未找到对应ID） 的本地化字符串。
        /// </summary>
        internal static string ERR_FACE_ID_NOT_EXITS {
            get {
                return ResourceManager.GetString("ERR_FACE_ID_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加人员失败（人员id重复） 的本地化字符串。
        /// </summary>
        internal static string ERR_FACE_ID_REPEAT {
            get {
                return ResourceManager.GetString("ERR_FACE_ID_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像中人脸不完整 的本地化字符串。
        /// </summary>
        internal static string ERR_FACE_INCOMPLETE {
            get {
                return ResourceManager.GetString("ERR_FACE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单个人员最大支持5张图像 的本地化字符串。
        /// </summary>
        internal static string ERR_FACES_NUM {
            get {
                return ResourceManager.GetString("ERR_FACES_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能授权失败 的本地化字符串。
        /// </summary>
        internal static string ERR_FUNC_AUTH {
            get {
                return ResourceManager.GetString("ERR_FUNC_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能已授权 的本地化字符串。
        /// </summary>
        internal static string ERR_FUNC_AUTHORIZED {
            get {
                return ResourceManager.GetString("ERR_FUNC_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取人脸特征失败（须保证图像中有且仅有一张人脸） 的本地化字符串。
        /// </summary>
        internal static string ERR_GET_FACE_FEATURE {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询人脸失败（无当前记录） 的本地化字符串。
        /// </summary>
        internal static string ERR_GET_FACE_ID {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸提取器未初始化（请调用HA_InitFaceModel初始化） 的本地化字符串。
        /// </summary>
        internal static string ERR_GET_FACE_INIT {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像解码失败 的本地化字符串。
        /// </summary>
        internal static string ERR_IMAGE_DECODE {
            get {
                return ResourceManager.GetString("ERR_IMAGE_DECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在，请检查图片路径是否正确 的本地化字符串。
        /// </summary>
        internal static string ERR_IMAGE_PATH {
            get {
                return ResourceManager.GetString("ERR_IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像太大，用于提取特征的jpg图像不能超过10M，下发到相机的jpg图像 宽高不能超过128x128 的本地化字符串。
        /// </summary>
        internal static string ERR_IMAGE_SIZE {
            get {
                return ResourceManager.GetString("ERR_IMAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检出指定个数红外光目标 的本地化字符串。
        /// </summary>
        internal static string ERR_INFRARED_TARGET {
            get {
                return ResourceManager.GetString("ERR_INFRARED_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数非法（缺失或错误的参数） 的本地化字符串。
        /// </summary>
        internal static string ERR_INVALID_PARAM {
            get {
                return ResourceManager.GetString("ERR_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的同步操作 的本地化字符串。
        /// </summary>
        internal static string ERR_INVALID_SYNC_MODE {
            get {
                return ResourceManager.GetString("ERR_INVALID_SYNC_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少归一化图像 的本地化字符串。
        /// </summary>
        internal static string ERR_LACK_TWISTIMGE {
            get {
                return ResourceManager.GetString("ERR_LACK_TWISTIMGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸尺寸太小，人脸轮廓必须大于96*96 的本地化字符串。
        /// </summary>
        internal static string ERR_MIN_FACE {
            get {
                return ResourceManager.GetString("ERR_MIN_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张嘴幅度过大 的本地化字符串。
        /// </summary>
        internal static string ERR_MOUTH_OPEN {
            get {
                return ResourceManager.GetString("ERR_MOUTH_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string ERR_NONE {
            get {
                return ResourceManager.GetString("ERR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未实现（设备版本较低不支持当前操作） 的本地化字符串。
        /// </summary>
        internal static string ERR_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求数据包包含不合法字段 的本地化字符串。
        /// </summary>
        internal static string ERR_PACKET_DATA {
            get {
                return ResourceManager.GetString("ERR_PACKET_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议版本不匹配，请确认SDK和相机固件版本 的本地化字符串。
        /// </summary>
        internal static string ERR_PROTOCAL_VER {
            get {
                return ResourceManager.GetString("ERR_PROTOCAL_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的云台控制，目前只支持5：变倍（放大） 6：变倍（缩小） 7：聚焦（拉近） 8：聚焦（拉远） 的本地化字符串。
        /// </summary>
        internal static string ERR_PTZ_CTRL {
            get {
                return ResourceManager.GetString("ERR_PTZ_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的控制模式，1：一次运动 2：启动 3：停止 的本地化字符串。
        /// </summary>
        internal static string ERR_PTZ_CTRL_MODE {
            get {
                return ResourceManager.GetString("ERR_PTZ_CTRL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人像质量太差不满足注册条件 的本地化字符串。
        /// </summary>
        internal static string ERR_QVALUE_TOO_SMALL {
            get {
                return ResourceManager.GetString("ERR_QVALUE_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据失败 的本地化字符串。
        /// </summary>
        internal static string ERR_READ_DATA {
            get {
                return ResourceManager.GetString("ERR_READ_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特征数据版本不匹配 的本地化字符串。
        /// </summary>
        internal static string ERR_REPLYCODE_FEATURE_VERSION {
            get {
                return ResourceManager.GetString("ERR_REPLYCODE_FEATURE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的操作请求 的本地化字符串。
        /// </summary>
        internal static string ERR_REQUEST_CMD {
            get {
                return ResourceManager.GetString("ERR_REQUEST_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前相机只支持存一张模板图像，pictureFlags必须&lt;=1 的本地化字符串。
        /// </summary>
        internal static string ERR_SAVE_IMG_NUM {
            get {
                return ResourceManager.GetString("ERR_SAVE_IMG_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的串口编号（目前只支持HA_SERIAL_RS485和HA_SERIAL_RS232） 的本地化字符串。
        /// </summary>
        internal static string ERR_SERIAL_INDEX {
            get {
                return ResourceManager.GetString("ERR_SERIAL_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统不匹配（操作设备不是人脸抓拍相机） 的本地化字符串。
        /// </summary>
        internal static string ERR_SYS_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERR_SYS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作系统繁忙 的本地化字符串。
        /// </summary>
        internal static string ERR_SYSTEM_BUSY {
            get {
                return ResourceManager.GetString("ERR_SYSTEM_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启系统失败 的本地化字符串。
        /// </summary>
        internal static string ERR_SYSTEM_REBOOT {
            get {
                return ResourceManager.GetString("ERR_SYSTEM_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作超时（设备在规定时间内未响应当前操作） 的本地化字符串。
        /// </summary>
        internal static string ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像中人脸数不为1 的本地化字符串。
        /// </summary>
        internal static string ERR_TOO_MUCH_FACE {
            get {
                return ResourceManager.GetString("ERR_TOO_MUCH_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归一化图像失败 的本地化字符串。
        /// </summary>
        internal static string ERR_TWIST_FACE {
            get {
                return ResourceManager.GetString("ERR_TWIST_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能未授权 的本地化字符串。
        /// </summary>
        internal static string ERR_UN_AUTH {
            get {
                return ResourceManager.GetString("ERR_UN_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接（网络问题） 的本地化字符串。
        /// </summary>
        internal static string ERR_UNCONNECTED {
            get {
                return ResourceManager.GetString("ERR_UNCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string ERR_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员数量已达上限 的本地化字符串。
        /// </summary>
        internal static string ERR_UPPER_LIMIT {
            get {
                return ResourceManager.GetString("ERR_UPPER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本不匹配 的本地化字符串。
        /// </summary>
        internal static string ERR_VERSION_MATCH {
            get {
                return ResourceManager.GetString("ERR_VERSION_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检出指定个数可见光目标 的本地化字符串。
        /// </summary>
        internal static string ERR_VISIBLE_TARGET {
            get {
                return ResourceManager.GetString("ERR_VISIBLE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韦根卡号不支持模糊查询 的本地化字符串。
        /// </summary>
        internal static string ERR_WG_QUERY_MODE {
            get {
                return ResourceManager.GetString("ERR_WG_QUERY_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据失败 的本地化字符串。
        /// </summary>
        internal static string ERR_WRITE_DATA {
            get {
                return ResourceManager.GetString("ERR_WRITE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光照不均匀 的本地化字符串。
        /// </summary>
        internal static string ERR_YINYANG_FACE {
            get {
                return ResourceManager.GetString("ERR_YINYANG_FACE", resourceCulture);
            }
        }
    }
}
