//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaSdkWrapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaSdkWrapper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可见光红外光像差过大.
        /// </summary>
        internal static string ERR_ABERRATION_TOO_BIG {
            get {
                return ResourceManager.GetString("ERR_ABERRATION_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸俯仰角太大.
        /// </summary>
        internal static string ERR_ANGLE_PITCH {
            get {
                return ResourceManager.GetString("ERR_ANGLE_PITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸不正.
        /// </summary>
        internal static string ERR_ANGLE_ROLL {
            get {
                return ResourceManager.GetString("ERR_ANGLE_ROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸侧偏角太大.
        /// </summary>
        internal static string ERR_ANGLE_YAW {
            get {
                return ResourceManager.GetString("ERR_ANGLE_YAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启应用程序失败.
        /// </summary>
        internal static string ERR_APP_REBOOT {
            get {
                return ResourceManager.GetString("ERR_APP_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认证失败.
        /// </summary>
        internal static string ERR_AUTH_FAILED {
            get {
                return ResourceManager.GetString("ERR_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 压缩图像失败.
        /// </summary>
        internal static string ERR_ENCODE_JPG {
            get {
                return ResourceManager.GetString("ERR_ENCODE_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提取特征失败.
        /// </summary>
        internal static string ERR_EXTRACT_FEATURE {
            get {
                return ResourceManager.GetString("ERR_EXTRACT_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改人脸特征失败（未找到对应ID）.
        /// </summary>
        internal static string ERR_FACE_ID_NOT_EXITS {
            get {
                return ResourceManager.GetString("ERR_FACE_ID_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加人员失败（人员id重复）.
        /// </summary>
        internal static string ERR_FACE_ID_REPEAT {
            get {
                return ResourceManager.GetString("ERR_FACE_ID_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像中人脸不完整.
        /// </summary>
        internal static string ERR_FACE_INCOMPLETE {
            get {
                return ResourceManager.GetString("ERR_FACE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单个人员最大支持5张图像.
        /// </summary>
        internal static string ERR_FACES_NUM {
            get {
                return ResourceManager.GetString("ERR_FACES_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提取人脸特征失败（须保证图像中有且仅有一张人脸）.
        /// </summary>
        internal static string ERR_GET_FACE_FEATURE {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询人脸失败（无当前记录）.
        /// </summary>
        internal static string ERR_GET_FACE_ID {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸提取器未初始化（请调用HA_InitFaceModel初始化）.
        /// </summary>
        internal static string ERR_GET_FACE_INIT {
            get {
                return ResourceManager.GetString("ERR_GET_FACE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像解码失败.
        /// </summary>
        internal static string ERR_IMAGE_DECODE {
            get {
                return ResourceManager.GetString("ERR_IMAGE_DECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件不存在，请检查图片路径是否正确.
        /// </summary>
        internal static string ERR_IMAGE_PATH {
            get {
                return ResourceManager.GetString("ERR_IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像太大，用于提取特征的jpg图像不能超过10M，下发到相机的jpg图像 宽高不能超过128x128.
        /// </summary>
        internal static string ERR_IMAGE_SIZE {
            get {
                return ResourceManager.GetString("ERR_IMAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检出指定个数红外光目标.
        /// </summary>
        internal static string ERR_INFRARED_TARGET {
            get {
                return ResourceManager.GetString("ERR_INFRARED_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数非法（缺失或错误的参数）.
        /// </summary>
        internal static string ERR_INVALID_PARAM {
            get {
                return ResourceManager.GetString("ERR_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的同步操作.
        /// </summary>
        internal static string ERR_INVALID_SYNC_MODE {
            get {
                return ResourceManager.GetString("ERR_INVALID_SYNC_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺少归一化图像.
        /// </summary>
        internal static string ERR_LACK_TWISTIMGE {
            get {
                return ResourceManager.GetString("ERR_LACK_TWISTIMGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸尺寸太小，人脸轮廓必须大于96*96.
        /// </summary>
        internal static string ERR_MIN_FACE {
            get {
                return ResourceManager.GetString("ERR_MIN_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 张嘴幅度过大.
        /// </summary>
        internal static string ERR_MOUTH_OPEN {
            get {
                return ResourceManager.GetString("ERR_MOUTH_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        internal static string ERR_NONE {
            get {
                return ResourceManager.GetString("ERR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未实现（设备版本较低不支持当前操作）.
        /// </summary>
        internal static string ERR_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("ERR_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求数据包包含不合法字段.
        /// </summary>
        internal static string ERR_PACKET_DATA {
            get {
                return ResourceManager.GetString("ERR_PACKET_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协议版本不匹配，请确认SDK和相机固件版本.
        /// </summary>
        internal static string ERR_PROTOCAL_VER {
            get {
                return ResourceManager.GetString("ERR_PROTOCAL_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的云台控制，目前只支持5：变倍（放大） 6：变倍（缩小） 7：聚焦（拉近） 8：聚焦（拉远）.
        /// </summary>
        internal static string ERR_PTZ_CTRL {
            get {
                return ResourceManager.GetString("ERR_PTZ_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的控制模式，1：一次运动 2：启动 3：停止.
        /// </summary>
        internal static string ERR_PTZ_CTRL_MODE {
            get {
                return ResourceManager.GetString("ERR_PTZ_CTRL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人像质量太差不满足注册条件.
        /// </summary>
        internal static string ERR_QVALUE_TOO_SMALL {
            get {
                return ResourceManager.GetString("ERR_QVALUE_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取数据失败.
        /// </summary>
        internal static string ERR_READ_DATA {
            get {
                return ResourceManager.GetString("ERR_READ_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特征数据版本不匹配.
        /// </summary>
        internal static string ERR_REPLYCODE_FEATURE_VERSION {
            get {
                return ResourceManager.GetString("ERR_REPLYCODE_FEATURE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的操作请求.
        /// </summary>
        internal static string ERR_REQUEST_CMD {
            get {
                return ResourceManager.GetString("ERR_REQUEST_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前相机只支持存一张模板图像，pictureFlags必须&lt;=1.
        /// </summary>
        internal static string ERR_SAVE_IMG_NUM {
            get {
                return ResourceManager.GetString("ERR_SAVE_IMG_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的串口编号（目前只支持HA_SERIAL_RS485和HA_SERIAL_RS232）.
        /// </summary>
        internal static string ERR_SERIAL_INDEX {
            get {
                return ResourceManager.GetString("ERR_SERIAL_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统不匹配（操作设备不是人脸抓拍相机）.
        /// </summary>
        internal static string ERR_SYS_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERR_SYS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作系统繁忙.
        /// </summary>
        internal static string ERR_SYSTEM_BUSY {
            get {
                return ResourceManager.GetString("ERR_SYSTEM_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启系统失败.
        /// </summary>
        internal static string ERR_SYSTEM_REBOOT {
            get {
                return ResourceManager.GetString("ERR_SYSTEM_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作超时（设备在规定时间内未响应当前操作）.
        /// </summary>
        internal static string ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像中人脸数不为1.
        /// </summary>
        internal static string ERR_TOO_MUCH_FACE {
            get {
                return ResourceManager.GetString("ERR_TOO_MUCH_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归一化图像失败.
        /// </summary>
        internal static string ERR_TWIST_FACE {
            get {
                return ResourceManager.GetString("ERR_TWIST_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未连接（网络问题）.
        /// </summary>
        internal static string ERR_UNCONNECTED {
            get {
                return ResourceManager.GetString("ERR_UNCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        internal static string ERR_UNDEFINED {
            get {
                return ResourceManager.GetString("ERR_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人员数量已达上限.
        /// </summary>
        internal static string ERR_UPPER_LIMIT {
            get {
                return ResourceManager.GetString("ERR_UPPER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本不匹配.
        /// </summary>
        internal static string ERR_VERSION_MATCH {
            get {
                return ResourceManager.GetString("ERR_VERSION_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检出指定个数可见光目标.
        /// </summary>
        internal static string ERR_VISIBLE_TARGET {
            get {
                return ResourceManager.GetString("ERR_VISIBLE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韦根卡号不支持模糊查询.
        /// </summary>
        internal static string ERR_WG_QUERY_MODE {
            get {
                return ResourceManager.GetString("ERR_WG_QUERY_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入数据失败.
        /// </summary>
        internal static string ERR_WRITE_DATA {
            get {
                return ResourceManager.GetString("ERR_WRITE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光照不均匀.
        /// </summary>
        internal static string ERR_YINYANG_FACE {
            get {
                return ResourceManager.GetString("ERR_YINYANG_FACE", resourceCulture);
            }
        }
    }
}
