//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDKClientSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDKClientSharp.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加人像.
        /// </summary>
        internal static string AddFaceAction {
            get {
                return ResourceManager.GetString("AddFaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接相机 {0} {1}.
        /// </summary>
        internal static string ConnectCamMsg {
            get {
                return ResourceManager.GetString("ConnectCamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除人像.
        /// </summary>
        internal static string DeleteFaceAction {
            get {
                return ResourceManager.GetString("DeleteFaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除 {0}.
        /// </summary>
        internal static string DeleteFaceMsg {
            get {
                return ResourceManager.GetString("DeleteFaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生错误：{0} ({1}).
        /// </summary>
        internal static string ErrorWithErrorMsg {
            get {
                return ResourceManager.GetString("ErrorWithErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有.
        /// </summary>
        internal static string FaceType_All {
            get {
                return ResourceManager.GetString("FaceType.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黑名单.
        /// </summary>
        internal static string FaceType_BlackName {
            get {
                return ResourceManager.GetString("FaceType.BlackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通.
        /// </summary>
        internal static string FaceType_Normal {
            get {
                return ResourceManager.GetString("FaceType.Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 白名单.
        /// </summary>
        internal static string FaceType_WhiteName {
            get {
                return ResourceManager.GetString("FaceType.WhiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精确匹配.
        /// </summary>
        internal static string MatchingMode_Exactly {
            get {
                return ResourceManager.GetString("MatchingMode.Exactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模糊匹配.
        /// </summary>
        internal static string MatchingMode_Fuzzy {
            get {
                return ResourceManager.GetString("MatchingMode.Fuzzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询人像.
        /// </summary>
        internal static string QueryFaceAction {
            get {
                return ResourceManager.GetString("QueryFaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规则{0}.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测图像：{0}.
        /// </summary>
        internal static string ValidateImageMsg {
            get {
                return ResourceManager.GetString("ValidateImageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已过期.
        /// </summary>
        internal static string ValidTo_Expired {
            get {
                return ResourceManager.GetString("ValidTo.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永不过期.
        /// </summary>
        internal static string ValidTo_NeverExpire {
            get {
                return ResourceManager.GetString("ValidTo.NeverExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定时间.
        /// </summary>
        internal static string ValidTo_Specified {
            get {
                return ResourceManager.GetString("ValidTo.Specified", resourceCulture);
            }
        }
    }
}
